### ISSUE TITLE
Advices method formatted() for class java.util.Locale

### ISSUE THREAD

**Issue by Fenmore** [Feuermagier/autograder#384] opened 2024-01-18 20:30 UTC
### Summary

Using a Locale with string format results in the advice to use 'Locale.ENGLISH.formatted("%f", price)' instead, even though this method doesn't exist in the class java.util.Locale.

### Lint Name

USE_STRING_FORMATTED

### Reproducer

```java
import java.util.Locale;

public class Formatter {

    public static String formatPrice(double price) {
        return String.format(Locale.ENGLISH, "%f", price);
    }
}
```

**Comment by Luro02** [comment] 2024-01-18 20:43
Duplicate of #380

**Closed by Luro02** 2024-01-18 20:43 UTC
Labels: bug, false-positive
